# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/muttti/123/output/vivado_project/pcileech_firmware.srcs/sources_1/ip/pcie_7x_bridge/pcie_7x_bridge.xci
# IP: The module: 'pcie_7x_bridge' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/muttti/123/output/vivado_project/pcileech_firmware.gen/sources_1/ip/pcie_7x_bridge/source/pcie_7x_bridge-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_bridge'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/muttti/123/output/vivado_project/pcileech_firmware.gen/sources_1/ip/pcie_7x_bridge/source/ip_xilinx_pcie_2_1_7x_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_bridge'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/muttti/123/output/vivado_project/pcileech_firmware.gen/sources_1/ip/pcie_7x_bridge/synth/pcie_7x_bridge_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_bridge'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/muttti/123/output/vivado_project/pcileech_firmware.srcs/sources_1/ip/pcie_7x_bridge/pcie_7x_bridge.xci
# IP: The module: 'pcie_7x_bridge' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/muttti/123/output/vivado_project/pcileech_firmware.gen/sources_1/ip/pcie_7x_bridge/source/pcie_7x_bridge-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_bridge'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/muttti/123/output/vivado_project/pcileech_firmware.gen/sources_1/ip/pcie_7x_bridge/source/ip_xilinx_pcie_2_1_7x_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_bridge'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/muttti/123/output/vivado_project/pcileech_firmware.gen/sources_1/ip/pcie_7x_bridge/synth/pcie_7x_bridge_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_bridge'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
